# -*- coding: utf-8 -*-
"""whileloop.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ROYN6rYkJ4D1y2Inzitf3tipEcA17IT2
"""

a=1                     
while a<=20:
    if a%2==0:
     print(a)
    a+=1
a=0

while a<=20:
  print(a)
  a+=2

a=1
while a<=20:
    if a%2==1:
     print(a)
    a+=1

a=1
while a<=10:

    print(a)
    a+=1

a=0
while a<=10:
    print(a)s
    a+=1
  

i=1
while i<=10:
  print(i,i*i)
  i+=1

n=int(input("take a parttern"))
i=0
while i<n:
  print("*"*i)
  i+=1



a=int(input("enter a number"))
i=1
while i<=a:
  print("*"*a)
  i=i+1

i=10
while i<=300:
  print(i, end=" ")
  i+=10



i=105
while i>=7:
  print(i,end=" ")
  i-=7

a=10
while a>=0:
 print(a)
 a-=1

a=1
sum=0
while a<=10:
  sum+=a
  a+=1
print(sum)

n=1
while n<=10:
  print(5(n+10))
  n+=1

a=0
sum=0
while a<=20:
  sum+=a
  a+=2
print(sum)

i=int(input("Enter a no "))
j=1
while j<=10:
  print(i*j)
  j+=1

#Write a program to display all even numbers that fall between two numbers (exclusive both numbers)
#entered by the user

n1= 8
n2= 20
i=n1+2
while i<=n2-1:
  print(i)
  i+=2

#Write a program to check whether a number is prime or not.
n=int(input("Enter a no"))
i=2

while i<=n:
  if n%i==0:
   print("non prime")
   i+=1
   break
else:
  print(" prime")

#Write a program to find the product of the digits of a number accepted from the user
i=int(input("Enter a no "))
while i<=4:
  print(i+j)
  i+=1

#factors
n=int(input("Enter a no"))
i=1
while i<=n:
  if n%i==0 :
    print(i)
  i+=1

n=int(input("Enter a no"))
print("Factors are")
i=1
count=0
while i<=n:
  if n%i==0:
    count=count+1
    print(i,end=",")
  i+=1
if count==2:
  print("prime")
else:
  print("not prime")

n=int(input("Enter a no"))
i=1
count=0
while i<=n:
  if n%i==0 :
    count=count+1
  i+=1
if count<=2:
  print("prime")
else:
  print("non prima")

i=1

while i<=4:
    j=1
    print("Anjali", end="")
    while j<=3:
        print("Navgururkul" , end="")
        j+=1
    i+=1
    print()

i=0
while i<=5:
  j=1
  while j<=i+1:
    print(i+j,end="")
    j+=1
  i+=1
  print()

i=5
while i<=5:
  print("*"*i)
  i-=1
  print()

[11:45 pm, 28/04/2022] Pankha: x=45
y=105
z=78
if x>y and x>z:
    print("x is greater than y and z")
elif z>y and z>x:
    print("z is greater than y and x")
else:
    print("y is greater than x and z")


x=-1
if x>0:
    print("x is positive")
elif x>0:
    print("x is negative")
else:
    print("x is equal to zero")
    
x=35
if x%5==0:
    print("x is divisible by 5")
elif x%11==0:
    print("x is divisible by 11")
else:
    print("x is divisible by 11")
    
x=85
if x%2==1:
        print("x is odd")
else:
    print("x is even")
    

x=2021
if x%4==0:
    print("it is a leap year")
else :
    print("it is not a leap year")
    
a=7
if type(a) == int or type(a)==float :
    print("It is number")
else:
    print("it is alphabet")

    
x=str(input("enter an alphabet:"  ))
y="aeiou"
if x in y:
    print("It is a vowel")
else:
    print("It is a consonant")
[11:45 pm, 28/04/2022] Pankha: x=input("Enter a sentence:")
y=int(input("1.word count\n2.change case\n3.Length of string\n4.Split the sentence\nEnter your choice"))
k=x.split(" ")
if y==1:
    print(f' the no of words are: {len(k)}')
elif y==2:
    print(f'the sentence in upper case: {x.upper()}')
elif y==3:
    print(f'the sentence in {len(x)}' )
elif y==4:
    print(f'the sentence in{k}')
else:
    print("Enter a valid input")
[11:46 pm, 28/04/2022] Pankha: ch = input("Please Enter Any Character : ")
 
if((ch >= 'a' and ch <= 'z') or (ch >= 'A' and ch <= 'Z')): 
    print("The Given Character ", ch, "is an Alphabet") 
elif(ch >= '0' and ch <= '9'):
    print("The Given Character ", ch, "is a Digit")
else:
    print("The Given Character ", ch, "is a Special Character")
[11:46 pm, 28/04/2022] Pankha: input1=input("Please enter any aplhabet:  ")
if input1>='a' and ch<='z':
    print("the given alphabet is in lowercase")
if input1>='A' and ch<='Z':
    print("the given alphabet is in uppercase")
[11:46 pm, 28/04/2022] Pankha: number = int(input("Enter a number"))
if number==1:
    print("Sunday")
elif number==2:
    print("Monday")
elif number==3:
    print("Tuesday")
elif number==4:
    print("Wednesday") 
elif number==5:
    print("Thursday")
elif number==6:
    print("Friday")
elif number==7:
    print("Saturday")
else:
    print("you entered number greater than7")
[11:46 pm, 28/04/2022] Pankha: number = int(input("Enter a number"))
if number==1 or 3 or 5 or 7 or 8 or 10 or 12 :
    print("the month has 31 days")
elif number==2:
    print("the month has 29 days")
elif number==4 or 6 or 9:
    print("the month has 30 days")
else:
    print("You can only input numbers between 1 to 12")
[11:47 pm, 28/04/2022] Pankha: x=500
[11:47 pm, 28/04/2022] Pankha: amt=int(input("Enter Amount\n"))

if amt>=500:
    note500=amt//500
    amt=amt-note500*500
if amt>=100:
    note100=amt//100
    amt=amt-note100*100
if amt>=50:
    note50=amt//50
    amt=amt-note50*50
if amt>=20:
    note20=amt//20
    amt=amt-note20*20
if amt>=10:
    note10=amt//10
    amt=amt-note10*10
if amt>=5:
    note5=amt//5
    amt=amt-note5*5
if amt>=2:
    note2=amt//2
    amt=amt-note2*2
if amt>=1:
    note1=amt//1
    amt=amt-note1*1
print("500 \t=\t",note500)
print("100 \t= \t",note100)
print("50 \t= \t",note50)
print("20 \t= \t",note20)
print("10 \t= \t",note10)
print("5 \t= \t",note5)
print("2 \t= \t",note2)
print("1 \t= \t",note1)
[11:47 pm, 28/04/2022] Pankha: x=int(input("Enter 1st angle  "))
y=int(input("Enter 2nd angle  "))
z=int(input("Enter 3rd angle  "))

if x+y+z == 180:
    print("The triangle is possible")
else:
    print("triangle is not possible")
[11:47 pm, 28/04/2022] Pankha: x=int(input("Enter 1st side  "))
y=int(input("Enter 2nd side  "))
z=int(input("Enter 3rd side  "))

if (x+y)>z:
    print("The triangle is possible")
else:
    print("triangle is not possible")
[11:47 pm, 28/04/2022] Pankha: x=int(input("Enter 1st side  "))
y=int(input("Enter 2nd side  "))
z=int(input("Enter 3rd side  "))
if x==y==z:
     print("The triangle is equilateral")
elif x==y:
     print("Triangle is isoceles ")
else:
    print("Triangle is scalene")
[11:47 pm, 28/04/2022] Pankha: x=int(input("Enter the C.P "))
y=int(input("Enter the S.P "))
if x>y:
    print("You had a loss of Rs", x-y)
else:
    print("you had a profit of Rs ", y-x)
[11:48 pm, 28/04/2022] Pankha: rite a python program to input marks of five subjects Physics, Chemistry,
Biology, Mathematics and Computer. Calculate percentage and grade according
to following:
Percentage >= 90% : Grade A
Percentage >= 80% : Grade B
Percentage >= 70% : Grade C
Percentage >= 60% : Grade D
Percentage >= 40% : Grade E
Percentage < 40% : Grade F
[11:48 pm, 28/04/2022] Pankha: a=int(input("Enter marks of physics "))
b=int(input("Enter marks of chemistry "))
c=int(input("Enter marks of biology "))
d=int(input("Enter marks of Maths "))
e=int(input("Enter marks of Computer "))

Percentage = int((a+b+c+d+e)*100/500)
if Percentage >= 90.0:
    print("Grade A")
elif Percentage >= 80.0 : 
    print("Grade B")
elif Percentage >= 70.0 : 
    print("Grade C")
elif Percentage >= 60.0 : 
    print("Grade D")
elif Percentage >= 40.0 : 
    print("Grade E")
elif Percentage < 40.0 : 
    print("Grade F")
else:
    print("Invalid")
[11:48 pm, 28/04/2022] Pankha: x="45"
print(x[-1])

a="Welcome to my Blog"
print(a.find("B"))
str=input("Enter the String:")
len=0
while str[:len]:
    len+=1
print("Your Enter String is:", len)

a=int(input("Enter num 1 :"))
b=int(input("Enter num 2 :"))
c,d,e,f=a+b,a-b,a*b,a/b
print(c,d,e,f)

print(end="Enter the Number of Days: ")
num = int(input())

year = int(num/365)
week = int((num%365)/7)
days = int((num%365)%7)

print("\nYear: "+str(year)+", Week: "+str(week)+", Day: "+str(days))

#  input weight use if else kg to lb /0.45

weight=int(input("input weight: "))
unit=input("Enter unit lb or kg ")
kg=  0.45*weight
lb= weight/0.45
if unit == "kg":
  print("Weight in lb",lb)
elif unit == "lb":
  print("Weight in kg",kg)
else:
  print("Invalid input")

print("  *")
i=1
while i<=6:
  j=1
  while j<=i:
    if j==1:
      print(" "*j,"*"*j," "*i,"*",end="")
    j+=1
  i+=1
  print()

b="9.0"
c=float(b)
print(int(c))

#Write a program to print the first 10 natural numbers in reverse order.
i=10
while i>=1:
  print(i)
  i-=1
#Write a program to print the sum of the first 10 Natural numbers.
i=1
sum=0
while i<=10:
  i+=1
  sum+=i
print(sum)



print("How Many Row You Want To Print")
one= int(input())
print("Type 1 Or 0")
two = int(input())
new =bool(two)
if new == True:
    for i in range(1,one+1):
        for j in range(1,i+1):
            print("*",end=" ")
        print()
elif new ==False:
    for i in range(one,0,-1):
        for j in range(1,i+1):
            print("*", end="")
        print()

a=int(input(" "))
if a>=1 and a<=9:
  print(a**2)
elif a>=10 and a<=19:
  print(a**3)
else:
  print(a)

#A shop will give a discount of 10% if the cost of the purchased quantity is more than 1000. Ask the user
#for quantity, Suppose, one unit will cost 100. Judge and print total cost for user.
a=int(input("Enter quantity"))
b=int(input("Enter price"))
c=a*b
if c>1000:
  print(c-c*0.1)
else:
  print(c)

# 35. Write a program to accept the cost price of a bike and display the road tax to be paid according to the
# following criteria :
# a. Cost price (in Rs) Tax    # b. > 100000 15 %
# c. > 50000 and <= 100000 10%
# d. <= 50000 5%

a=int(input("enter cost of bike"))
if a> 100000:
  print("amt inc tax  ",a+a*15/100)
elif a > 50000 and a<= 100000:
  print("amt inc tax  ",a+a*10/100)
else:
  print("amt inc tax  ",a+a*5/100)

# Accept any city from the user and display the monument of that city.
# City Monument
# Delhi Red Fort
# Agra Taj Mahal
# Jaipur Jal Mahal
a=input("Enter a monument")
if a=="delhi":
  print("Red fort")
elif a=="agra":
  print("Taj Mahal")
elif a=="jaipur":
  print("Jal Mahal")
else:
  print("sorrycurrently only few cities are available")

a=int(input("Enter a no"))
b=int(input("Enter a no"))
c=int(input("Enter a no"))
if a>b:
  if a>c:
    print(a,"is largest")
elif b>c:
  if b>a:
    print(b,"is largest")
else:
  print(c,"c is largest")

a=int(input("Enter a no"))
b=int(input("Enter a no"))
c=int(input("Enter a no"))
if a<b:
  if a>c:
    print(a,"is second largest")
elif a>b:
  if a<c:
    print(a,"is second largest")
elif b>c:
  if b<a:
    print(b,"is second largest")
elif b<c:
  if b>a:
    print(b,"is second largest")
elif c>a:
  if c<b:
    print(c,"is second largest")
elif c<a:
  if c>b:
    print(c,"is second largest")
else:
  print("j")

a=int(input("Enter a no"))
b=int(input("Enter a no"))
c=int(input("Enter a no"))
if (a > b and a<c) or (a<b and a>c):
  print(a)
elif(b>a and b<c) or (b<a and b>c) :
  print(b)
else:
  print(c)

a=input("Enter a 3 no digit")


A=int(a[0])**3+int(a[1])**3+int(a[2])**3
B=100*int(a[0])+10*int(a[1])+int(a[2])
if A==B:
  print("Armstrong no")
else:
  print("not armstrong")

a=input("Enter a 3 no digit")
b=int(a[0])
print(b)

i=1
sum=0
while i<=100:
  num=int(input("Enter a no"))

i=0
while i<=4:
    print(i*-1)
    i+=1

i=1
sum=0
while i<=4:
  n=int(input("Enter a no"))
  if n>=52:
    sum+=n
    i+=10
  else:
    print("err")

i=1
sum=0
while i<=5:
  n= int(input("Enter a no"))
  sum=sum+n
  i+=1
print(sum/(i-1))

a=int(input("enter a number:"))
i=1
sum=0
while i<=a:
  b=int(input("my "))
  sum+=b
  i+=1
print(sum)

a=input("enter a number:")
i=10
sum=0
while i<=a:
  b=int(input("enter a number:"))
if a=="q":
  print("stop the loop")
else:

num=1001                 #we take a temp variable so that the VALUE OF num remains same otherwise it will become 0.
temp=num
reversed_num = 0
while temp> 0:
    reversed_num = reversed_num * 10 + temp%10
    temp //= 10
if num==reversed_num:
  print("Palindrome")
else:
  print("not palindrome")



num = int( input ( " ENTER THE NUMBER: " ) )
 
temporary = num
rev = 0
 
# looping the given input and reversing the value  
while temporary != 0:
	rev = ( rev * 10 ) + ( temporary % 10 )
	temporary = temporary // 10
 
if num == rev:
	print( " number is palindrome " )
else:
	print( " number is not palindrome " )

i=0
while i<=5:
  j=1
  while j<=i+1:
    print(i+j,end="") 
    j+=1
  i+=1
  print()

#decimal to binary
decimal = int(input("Enter the Decimal Number \n"))
binary = 0
i= 0
temp = decimal  
while(temp > 0):
    binary = ((temp%2)*(10**i))+binary
    temp = int(temp/2)
    i += 1
print(binary)

print(bin(15))

decimal = int(input("Enter the Decimal Number \n"))
binary = 0
i= 0
temp = decimal  
while(temp > 0):
    binary = (temp%2)
    temp =temp//2
    i += 1 
    print(binary)

num=int(input("Enter a no"))
i=1
while i<=num:
  print("*"*i)
  i+=1

num=int(input("Enter a no"))
i=num
while i>=0:
  print("*"*i)
  i-=1

a=int(input("enter a number "))
col=a*2-1
mid=col//2+1
i=1
while i<=a:
  j=1
  while j<=col:
    if i==a or i+j==mid+1 or j-i==mid-1:
      print("*",end=" ")
    else:
      print(end="  ")
    j+=1
  i+=1
  print()

n=5
    k = 2*n - 2
    i=0
    while i<=5: 
        j=0
        while j<=5: 
            print(end=" ") 
        k = k - 1
        while j in range(0, i+1): 
            print("* ", end="") 
            j+=1
        i+=1
        print("")

def triangle(n): 
      
    # number of spaces 
    k = 2*n - 2
  
    # outer loop to handle number of rows 
    for i in range(0, n): 
      
        # inner loop to handle number spaces 
        # values changing acc. to requirement 
        for j in range(0, k): 
            print(end=" ") 
      
        # decrementing k after each loop 
        k = k - 1
      
        # inner loop to handle number of columns 
        # values changing acc. to outer loop 
        for j in range(0, i+1): 
          
            # printing stars 
            print("* ", end="") 
      
        # ending line after each row 
        print("
") 
  
# Driver Code 
n = 5
triangle(n)

s= input("Enter a word ")
if "ing" in s:
  print(s+"ly")
elif len(s)>=3:
  print(s+"ing")
else:
  print("invalid")

#right sided pattern
i=1
while i <=5:
  j=1
  while j<=n-i-1:
    print(" ",end="")
    j+=1
  j=1
  while j<=i:
    print("*",end="")
    j+=1
  i+=1
  print()

#right sided numeric pattern
i=1
while i <=4:
  j=1
  while j<=n-i-1:
    print(" ",end="")
    j+=1
  j=1
  while j<=i:
    print(j,end="")
    j+=1
  i+=1
  print()

j=0
while j<=10:
  j+=1
  if j==5:
    continue
  print(j)

i=1
while i<=3:
  j=0
  i+=1
  while j<10:
    j+=1
    if j==4:
      continue
    print(j*i)

#factorial 
a=int(input("enter  :  "))
i=1
product=1
while i<=a:
  product*=i
  i+=1
print(product)

#Write a Python program to guess a number between 1 to 9
# i=1
guess_num=5
while : 
  num=int(input("Enter a no: "))
  if num<=9:
    print("great")
    break
  # i+=1
else:
  print("Enter no again")

#Write a Program to print all the characters in the string ‘COMPUTER’ using a while loop
i=0
sum1=0
str1="COMPUTER"
while i<len(str1):
  print(str1[i])
  i+=1

#Write a Python program to find those numbers which are divisible by 7 and multiple of 5, between 1500 and
#2700 (both included)
i=1500
while i<=2700:
  if i%7==0 and i%5==0:
    print(i)
  i+=1

num=int(input("enter a num "))
temp=num
sum=0
while temp>0:
  L_digit=temp%10
  sum=sum+ L_digit**len(str(num))
  temp=temp//10
  
if sum==num:
  print("armstrong")
else:
  print("not armstrong")   #mistake i was doing i was taking i as counter which is not required coz we run till temp become

num1=123
i=0
while i<0:
  num1=num1%10
  num1//=10
  print(num1)
  i+=1

n=int(input("Enter nos"))
i=1
while i <=n:
  j=1
  while j<=n-i:
    print(" ",end="")
    j+=1
  j=1
  while j<=2*i-1:
    print("*",end="")
    j+=1
  #print()
  i+=1
  print()

prime no seriesm
num=int(input("enter a no "))
last= int(input("enter last no"))
while num<=last:
  i=2
  while i<num:
    if num%i==0:
      break  
    i+=1
  else:
      print(num)
  num+=1
#  To find the sum of all prime numbers between 1 to N.


i=2
num= 30
count=0
while count<num:
  j=2
  while j<=int(i**0.5):
    if i%j==0:
      break
    j+=1  
  else:
      print(i)
      count+=1
  i+=1

i=int(input("Enter a no"))
if i==4:
  print("4")
else:
  if i==0:
    print(("0"))
  else:
    print("hh")

i=65
while i<=70:
  j=65
  while j<=i:
   print(chr(i),end=" ")
   j+=1
  i+=1
  print()

student_marks = [23, 45, 67, 89, 90, 54, 34, 21, 34, 23, 19, 28, 10, 45, 86, 87, 9]
list_length = len(student_marks)
index = 0
less_than50 = 0
more_than50 = 0
while index < list_length:
 marks = student_marks[index]
 if marks < 50:
  less_than50 = less_than50 + 1
 else:
  more_than50 = more_than50 + 1
 index = index + 1
print("Marks more than 50: " + str(more_than50))
print("Marks less than 50: " + str(less_than50))

n=int(input("Enter a no"))
i=1
count=0
while i<=n:
  if n%i==0:
    count=count+1
  if count>2:
    print(i)
  i+=1

k=0
i=1 
while i<5:
  j=0
  while j<i:
    k+=1
    print(k,end=" ")
    j+=1
  i+=1
  print()

a=int(input("enter a no"))
rev=0
b=a
while a>0:
  rev=rev*10+a%10
  a=a//10
if rev==b:
    print("palindrome")
else:
    print("no")

num=678
i=num:
print  (num%10)
print(num//10)

stri="python"
for i in range(1,len(stri)+1):
  for j in range(i) :
    print(stri[j],end="")
  print()

#valid parentheses
brac=input("enter brackets")
cont=[]
for i in brac:
  if len(cont)==0:
    cont.append(i)
  else:
    if i==")" and cont[-1]=="(": 
      cont.pop() 
    elif i=="]" and cont[-1]=="[":
      cont.pop()
    elif i=="}" and cont[-1]=="{":
      cont.pop()
    else:
      cont.append(i)
if len(cont)==0:
  print("valid")
else:
  print("invalid")

def convertFive(n):
   n=str(n)
   for i in n:
       if i=="0":
        n.replace("5","0")
   return int(n)
    
print(convertFive(1004))

a,b,c=3,2,1
if a>b:
  max=a
else:
  max=b

if max>c:
  max=max
else:
  max=c
print(max)

n=int(input())
i=1
count=0
while i<=n:
  num=int(input())
  
  i+=1
print(count)

